### ISSUE TITLE
Nil pointer dereference on context cancel when using WithEnvelopeStreamBuffer

### ISSUE THREAD

**Issue by jpmcb** [cloudfoundry/go-loggregator#48]
The log-store has ran into an issue trying to add the `loggregator.WithEnvelopeStreamBuffer` and `Stream` methods. When the provided context is canceled, which we do in our code to gracefully shutdown and handle hanging connections, a nil pointer is dereferenced causing a panic.

Here's a failing test that we were able to reproduce the error:
```golang
It("wont panic when context canceled", func() {
	producer, err := newFakeEventProducer()
	Expect(err).NotTo(HaveOccurred())

	// Producer will grab a port on start. When the producer is restarted,
	// it will grab the same port.
	producer.start()
	defer producer.stop()

	tlsConf, err := loggregator.NewIngressTLSConfig(
		fixture("CA.crt"),
		fixture("server.crt"),
		fixture("server.key"),
	)
	Expect(err).NotTo(HaveOccurred())

	var (
		mu     sync.Mutex
		missed int
	)
	addr := producer.addr
	c := loggregator.NewEnvelopeStreamConnector(
		addr,
		tlsConf,
		loggregator.WithEnvelopeStreamBuffer(5, func(m int) {
			mu.Lock()
			defer mu.Unlock()
			missed += m
		}),
	)

	// Use a context that can be canceled
	ctx, cancel := context.WithCancel(context.Background())
	rx := c.Stream(ctx, &loggregator_v2.EgressBatchRequest{})

	var count int
	// Read to allow the diode to notice it dropped data
	go func() {
		for range time.Tick(500 * time.Millisecond) {
			// Do not invoke rx while mu is locked
			l := len(rx())
			mu.Lock()
			count += l
			mu.Unlock()
		}
	}()

	Eventually(func() int {
		mu.Lock()
		defer mu.Unlock()
		return missed
	}).ShouldNot(BeZero())

	// When the context is canceled, the client panics
	cancel()

	mu.Lock()
	l := count
	mu.Unlock()
	Expect(l).ToNot(BeZero())
})
```
We copied this from "enables buffering" in `envelope_stream_connector_test.go` but added a cancel-able context.

When running we get:
```
❯ ./scripts/test
+ ginkgo -r -race
[1599068942] GoLoggregator Suite - 43/43 specs ••••••••••••••••••••••••••••••••panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x181778b]

goroutine 120 [running]:
code.cloudfoundry.org/go-loggregator/v8.(*OneToOneEnvelopeBatch).Next(...)
	/Users/jmcbride/workspace/go-loggregator/one_to_one_envelope_batch_diode.go:45
code.cloudfoundry.org/go-loggregator/v8_test.glob..func1.4.2(0xc000561a30, 0xc0000396e0, 0xc000039700)
	/Users/jmcbride/workspace/go-loggregator/envelope_stream_connector_test.go:186 +0x8c
created by code.cloudfoundry.org/go-loggregator/v8_test.glob..func1.4
	/Users/jmcbride/workspace/go-loggregator/envelope_stream_connector_test.go:183 +0x7b6

Ginkgo ran 1 suite in 8.758037312s
Test Suite Failed
```
We would expect this client library to be able to take a context that can be canceled as we cancel our context to start a graceful shutdown of our nozzle. Let me know if you have any questions!!

**Comment by JSchuenke** [comment]
I copied your failing test and it passed for me locally. Might have to do with Golang versions, I ran with version 1.14.3. Which did you use?

**Comment by jpmcb** [comment]
I may have coppied it wrong before, but here's the correct sequence to get the nil pointer dereference:

```golang
        FIt("wont panic when context canceled", func() {
		producer, err := newFakeEventProducer()
		Expect(err).NotTo(HaveOccurred())

		// Producer will grab a port on start. When the producer is restarted,
		// it will grab the same port.
		producer.start()
		defer producer.stop()

		tlsConf, err := loggregator.NewIngressTLSConfig(
			fixture("CA.crt"),
			fixture("server.crt"),
			fixture("server.key"),
		)
		Expect(err).NotTo(HaveOccurred())

		var (
			mu     sync.Mutex
			missed int
		)
		addr := producer.addr
		c := loggregator.NewEnvelopeStreamConnector(
			addr,
			tlsConf,
			loggregator.WithEnvelopeStreamBuffer(5, func(m int) {
				mu.Lock()
				defer mu.Unlock()
				missed += m
			}),
		)

		// Use a context that can be canceled
		ctx, cancel := context.WithCancel(context.Background())
		rx := c.Stream(ctx, &loggregator_v2.EgressBatchRequest{})

		var count int
		// Read to allow the diode to notice it dropped data
		go func() {
			for range time.Tick(500 * time.Millisecond) {
				// Do not invoke rx while mu is locked
				l := len(rx())
				mu.Lock()
				count += l
				mu.Unlock()
			}
		}()

		// When the context is canceled, the client panics
		cancel()

		Eventually(func() int {
			mu.Lock()
			defer mu.Unlock()
			return missed
		}).ShouldNot(BeZero())

		mu.Lock()
		l := count
		mu.Unlock()
		Expect(l).ToNot(BeZero())
	})
```
Note that canceling the context comes directly after the go routine has started firing.

Here's the output from running those tests:
```
+ ginkgo -r -race
[1601564954] GoLoggregator Suite - 1/43 specs SSSSSSSSSSSSSSSSSSSSSSSSpanic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x181b65b]

goroutine 40 [running]:
code.cloudfoundry.org/go-loggregator/v8.(*OneToOneEnvelopeBatch).Next(...)
        /Users/jmcbride/workspace/go-loggregator/one_to_one_envelope_batch_diode.go:45
code.cloudfoundry.org/go-loggregator/v8_test.glob..func1.4.2(0xc000535ed0, 0xc00047cfe0, 0xc00047d018)
        /Users/jmcbride/workspace/go-loggregator/envelope_stream_connector_test.go:186 +0x8c
created by code.cloudfoundry.org/go-loggregator/v8_test.glob..func1.4
        /Users/jmcbride/workspace/go-loggregator/envelope_stream_connector_test.go:183 +0x7b6

Ginkgo ran 1 suite in 8.975874429s
Test Suite Failed
```

Also of note, this was run with golang version:
```
❯ go version
go version go1.14.7 darwin/amd64
```

**Comment by Benjamintf1** [comment]
@jpmcb how does this work out for you?

**Comment by jpmcb** [comment]
I used a replace in our go mod with PR #49 and yes, this is fixed! No pointer de-referencing!
